import pandas as pd
import numpy as np

df=pd.read_csv('crime_dataset_india.csv')
df=df.dropna()
l1=np.array(df['Victim Age'])
l2=np.array(df['Victim Gender'])
l3=np.array(df['Crime Domain'])
l4=np.array(df['Weapon Used'])
l5=np.array([[l1,l2],[l3,l4]])
print("-------------------------------------------------")
print(l5.shape)
print("-------------------------------------------------")
print(type(l1))
print("-------------------------------------------------")
print(l5.ndim)
print("-------------------------------------------------")
print(l5.shape)
print("-------------------------------------------------")
print(l5.size)
print("-------------------------------------------------")
print(l5.dtype)
print("-------------------------------------------------")
l6=np.zeros(4)
print("l6 :", l6)
l7=np.zeros((2,3))
print("l7 :", l7)
l8=np.ones((3,4))
print("l8 :", l8)
l9=np.full(10,3)
print("l9 :", l9)
l10=np.arange(1,10,2)
print("l10 :", l10)
l11=np.linspace(2,10,5)
print("l11 :", l11)
l12=np.eye(3)
print("l12 :", l12)
l13=np.arange(1,10)
print("l13 reverse :", l13[::-1])
print("-------------------------------------------------")

print("l5[1] :", l5[1])
print("-------------------------------------------------")
print("l5[1,1] :", l5[1,1])
print("-------------------------------------------------")
print("l5[1,1][0] :", l5[1,1][0])
print("-------------------------------------------------")
print("l5[0] :", l5[0])
print("-------------------------------------------------")
print("l5[0,1] :", l5[0,1])
print("-------------------------------------------------")
print("l5[0,1][0] :", l5[0,1][0])
print("-------------------------------------------------")
print("l5 transpose :",l5.T)
print("-------------------------------------------------")
print("l5.T shape",l5.T.shape)

print("-------------------------------------------------")
a1=np.arange(1,10)
a2=np.arange(10,1,-1)
print("a1 + 10 :",a1+10)
print("sum of a1:",np.sum(a1))
print("dot product :",np.dot(a1,a2.T))
print("a1+a2 :",a1+a2)
print("np.add(a1,a2) :",np.add(a1,a2))
print("---------------------------------------------")
print("np.log :",np.log(a1))
print("---------------------------------------------")
print("np.tan :",np.tan(a1))
print("---------------------------------------------")
print("np.sin :",np.sin(a1))
print("---------------------------------------------")
print("np.exp :",np.exp(a1))
print("---------------------------------------------")
print("np.power :",np.power(a1,2))
print("---------------------------------------------")
print("np.sqrt :",np.sqrt(a1))


df['Date Reported']=pd.to_datetime(df['Date Reported'], format='%d-%m-%Y %H:%M')
df['Date Case Closed']=pd.to_datetime(df['Date Case Closed'], format='%d-%m-%Y %H:%M')
case_time=np.array(df['Date Case Closed']-df['Date Reported'])
print("mean case time :",np.mean(case_time))
print("median case time :",np.median(case_time))
print("----------------------------------------------")
good_case_time=case_time < np.median(case_time)
print("good case time :",good_case_time)
print(case_time[good_case_time])
print("np.where :",np.where(case_time<np.median(case_time),'good','bad'))
print("unique weapans :",np.unique(l4))