import pandas as pd
df=pd.read_csv('crime_dataset_india.csv')
# print("------------------------------------------------")
# print(df.shape)
# print("-------------------------------------------------")
# print(df.columns)
# print("-------------------------------------------------")
# print(df.head())
# print("-------------------------------------------------")
# print(df.info())
# print("-------------------------------------------------")
# print(df.describe())
# print("-------------------------------------------------")
# print(df.isnull().sum()) 
# print("-------------------------------------------------")
# print(df.iloc[100])
# print("-------------------------------------------------")
# print(df.iloc[90:100])
# print("-------------------------------------------------")
# print(df.loc[100])
# print("-------------------------------------------------")
# print(df.loc[90:100])
# print("-------------------------------------------------")
# print(df[df['City']=='Jaipur'])
# print("-------------------------------------------------")
# print(df[df["City"]=="Jaipur"].count())
# print("-------------------------------------------------")
df2=df.copy()
df2.dropna(inplace=True) 
df2['Date Reported']=pd.to_datetime(df2['Date Reported'], format='%d-%m-%Y %H:%M')
df2['Date Case Closed']=pd.to_datetime(df2['Date Case Closed'], format='%d-%m-%Y %H:%M')
df2['case_time']=df2['Date Case Closed']-df2['Date Reported']
print(df2.head())
df2.rename(columns={'case_time':'Case Duration'}, inplace=True)
print("-------------------------------------------------")
print(df2.head())
print("-------------------------------------------------")
print(df2['Crime Domain'].value_counts())
print("-------------------------------------------------")
print(df2.groupby('City')['Crime Domain'].value_counts())
print("-------------------------------------------------")
print(df2.groupby('Crime Domain')['Weapon Used'].value_counts())
print("-------------------------------------------------")
print(df2.sort_values(by='Case Duration', ascending=False).head())
print("-------------------------------------------------")
print(df2.groupby('City')['Case Duration'].agg(['min', 'max', 'mean']))
print("-------------------------------------------------")
print(pd.crosstab(df2['City'], df2['Crime Domain']))